import { Category } from '../types/product';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    slug: 'elektronik-gadget',
    name: 'Elektronik & Gadget',
    imageIcon: 'https://pngimg.com/uploads/smartphone/smartphone_PNG8514.png',
    description: 'Smartphones, wearables, audio, dan perlengkapan gadget terbaru garansi resmi.',
    bannerImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-1-1', slug: 'smartphone', name: 'Smartphone & HP', itemCount: 120 },
      { id: 'sub-1-2', slug: 'smartwatch', name: 'Smartwatch & Band', itemCount: 45 },
      { id: 'sub-1-3', slug: 'tws-audio', name: 'TWS & Headphone', itemCount: 88 },
      { id: 'sub-1-4', slug: 'powerbank', name: 'Powerbank & Charger', itemCount: 64 },
    ],
    itemCount: 317,
    isPopular: true,
    featuredTags: ['5G', 'Garansi Resmi TAM', 'Wireless Fast Charge'],
  },
  {
    id: 'cat-2',
    slug: 'fashion-pria',
    name: 'Fashion Pria',
    imageIcon: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
    description: 'Pakaian pria, sepatu sneakers, jaket, dan aksesoris gaya casual hingga formal.',
    bannerImage: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-2-1', slug: 'kaos-pria', name: 'Kaos & Polo', itemCount: 210 },
      { id: 'sub-2-2', slug: 'kemeja-pria', name: 'Kemeja & Flannel', itemCount: 95 },
      { id: 'sub-2-3', slug: 'sepatu-sneakers', name: 'Sneakers & Kasual', itemCount: 140 },
      { id: 'sub-2-4', slug: 'jaket-outerwear', name: 'Jaket & Hoodie', itemCount: 78 },
    ],
    itemCount: 523,
    isPopular: true,
    featuredTags: ['Oversized', 'Lokal Pride', 'Cotton Combed 24s'],
  },
  {
    id: 'cat-3',
    slug: 'fashion-wanita',
    name: 'Fashion Wanita',
    imageIcon: 'https://pngimg.com/uploads/dress/dress_PNG143.png',
    description: 'Dress, atasan wanita, tas branded, hijab, dan alas kaki modis terkini.',
    bannerImage: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-3-1', slug: 'dress-wanita', name: 'Dress & Terusan', itemCount: 180 },
      { id: 'sub-3-2', slug: 'tas-wanita', name: 'Tote Bag & Shoulder Bag', itemCount: 130 },
      { id: 'sub-3-3', slug: 'hijab-muslim', name: 'Hijab & Gamis', itemCount: 250 },
      { id: 'sub-3-4', slug: 'sepatu-wanita', name: 'Heels & Flatshoes', itemCount: 90 },
    ],
    itemCount: 650,
    isPopular: true,
    featuredTags: ['Korean Look', 'Minimalist', 'Linen Adem'],
  },
  {
    id: 'cat-4',
    slug: 'kecantikan-perawatan',
    name: 'Kecantikan & Perawatan',
    imageIcon: 'https://pngimg.com/uploads/perfume/perfume_PNG10287.png',
    description: 'Skincare original, serum pencerah, sunscreen, makeup, dan perawatan tubuh BPOM.',
    bannerImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-4-1', slug: 'serum-moisturizer', name: 'Serum & Pelembap', itemCount: 310 },
      { id: 'sub-4-2', slug: 'sunscreen', name: 'Sunscreen UV Protection', itemCount: 120 },
      { id: 'sub-4-3', slug: 'cushion-lip-tint', name: 'Cushion & Lip Tint', itemCount: 195 },
      { id: 'sub-4-4', slug: 'body-wash-lotion', name: 'Body Wash & Fragrance', itemCount: 85 },
    ],
    itemCount: 710,
    isPopular: true,
    featuredTags: ['BPOM Resmi', 'Niacinamide', 'Ceramide Barrier'],
  },
  {
    id: 'cat-5',
    slug: 'komputer-laptop',
    name: 'Komputer & Laptop',
    imageIcon: 'https://pngimg.com/uploads/laptop/laptop_PNG5917.png',
    description: 'Laptop kerja, gaming PC, monitor, mechanical keyboard, dan aksesoris PC.',
    bannerImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-5-1', slug: 'laptop-ultrabook', name: 'Laptop & Ultrabook', itemCount: 85 },
      { id: 'sub-5-2', slug: 'keyboard-mouse', name: 'Mechanical Keyboard & Mouse', itemCount: 140 },
      { id: 'sub-5-3', slug: 'monitor', name: 'Monitor IPS & Gaming', itemCount: 60 },
      { id: 'sub-5-4', slug: 'storage-ram', name: 'SSD NVMe & RAM', itemCount: 95 },
    ],
    itemCount: 380,
    isPopular: true,
    featuredTags: ['Mechanical Switch', 'Intel Core i7 / M3', '144Hz IPS'],
  },
  {
    id: 'cat-6',
    slug: 'rumah-tangga',
    name: 'Rumah Tangga & Perabotan',
    imageIcon: 'https://pngimg.com/uploads/sofa/sofa_PNG6956.png',
    description: 'Dekorasi rumah estetik, perabot minimalis, peralatan dapur, dan sprei lembut.',
    bannerImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-6-1', slug: 'peralatan-dapur', name: 'Peralatan Masak & Dapur', itemCount: 150 },
      { id: 'sub-6-2', slug: 'dekorasi-kamar', name: 'Lampu Meja & Aromaterapi', itemCount: 110 },
      { id: 'sub-6-3', slug: 'perabot-meja-kursi', name: 'Meja Ergonomis & Kursi', itemCount: 75 },
    ],
    itemCount: 335,
    isPopular: true,
    featuredTags: ['Estetik Scandinavian', 'Anti Lengket Granite', 'Bahan Kayu Jati'],
  },
  {
    id: 'cat-7',
    slug: 'makanan-minuman',
    name: 'Makanan & Minuman',
    imageIcon: 'https://pngimg.com/uploads/burger_sandwich/burger_sandwich_PNG4114.png',
    description: 'Camilan lokal nusantara, biji kopi artisan, frozen food, dan minuman sehat.',
    bannerImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-7-1', slug: 'kopi-artisan', name: 'Kopi Nusantara (Biji/Bubuk)', itemCount: 125 },
      { id: 'sub-7-2', slug: 'camilan-keripik', name: 'Keripik & Snack Lokal', itemCount: 210 },
      { id: 'sub-7-3', slug: 'madu-herbal', name: 'Madu Murni & Minuman Herbal', itemCount: 95 },
    ],
    itemCount: 430,
    isPopular: false,
    featuredTags: ['100% Halal', 'Arabika Gayo', 'Tanpa Pengawet'],
  },
  {
    id: 'cat-8',
    slug: 'olahraga-outdoor',
    name: 'Olahraga & Outdoor',
    imageIcon: 'https://pngimg.com/uploads/football/football_PNG52759.png',
    description: 'Peralatan gym rumahan, jersey, raket badminton, matras yoga, dan perlengkapan hiking.',
    bannerImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-8-1', slug: 'badminton-tennis', name: 'Raket & Shuttlecock', itemCount: 80 },
      { id: 'sub-8-2', slug: 'gym-fitness', name: 'Dumbbell & Resistance Band', itemCount: 110 },
      { id: 'sub-8-3', slug: 'camping-hiking', name: 'Tenda & Carrier Outdoor', itemCount: 70 },
    ],
    itemCount: 260,
    isPopular: false,
    featuredTags: ['Waterproof', 'Carbon Graphite', 'Dri-Fit'],
  },
  {
    id: 'cat-9',
    slug: 'ibu-bayi',
    name: 'Ibu & Bayi',
    imageIcon: 'https://pngimg.com/uploads/baby_bottle/baby_bottle_PNG24.png',
    description: 'Popok higienis, susu formula, pakaian bayi lembut, dan perlengkapan stroller.',
    bannerImage: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-9-1', slug: 'popok-bayi', name: 'Popok & Wipes', itemCount: 90 },
      { id: 'sub-9-2', slug: 'baju-bayi', name: 'Baju Katun Organik', itemCount: 130 },
      { id: 'sub-9-3', slug: 'stroller-carrier', name: 'Stroller & Gendongan', itemCount: 45 },
    ],
    itemCount: 265,
    isPopular: false,
    featuredTags: ['Hypoallergenic', 'BPA Free', 'Katun Lembut'],
  },
  {
    id: 'cat-10',
    slug: 'hobi-koleksi',
    name: 'Hobi & Koleksi',
    imageIcon: 'https://pngimg.com/uploads/gamepad/gamepad_PNG63.png',
    description: 'Action figure, diecast, kartu TCG, alat musik, dan peralatan fotografi.',
    bannerImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-10-1', slug: 'action-figure', name: 'Gundam & Anime Figures', itemCount: 150 },
      { id: 'sub-10-2', slug: 'diecast', name: 'Hotwheels & Skala 1:64', itemCount: 95 },
      { id: 'sub-10-3', slug: 'alat-musik', name: 'Gitar Akustik & Kalimba', itemCount: 60 },
    ],
    itemCount: 305,
    isPopular: false,
    featuredTags: ['Original Bandai', 'Collector Item', 'Mint In Box'],
  },
  {
    id: 'cat-11',
    slug: 'otomotif',
    name: 'Otomotif & Aksesoris',
    imageIcon: 'https://pngimg.com/uploads/car_wheel/car_wheel_PNG23302.png',
    description: 'Helm SNI, oli motor/mobil, dashcam, interkom bluetooth, dan car care kit.',
    bannerImage: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-11-1', slug: 'helm-motor', name: 'Helm Fullface & Halfface SNI', itemCount: 110 },
      { id: 'sub-11-2', slug: 'car-care', name: 'Shampoo & Pengkilap Body', itemCount: 85 },
      { id: 'sub-11-3', slug: 'intercom-dashcam', name: 'Intercom & Dashcam Mobil', itemCount: 65 },
    ],
    itemCount: 260,
    isPopular: false,
    featuredTags: ['Standar SNI / DOT', 'Full HD 1080p', 'Hydrophobic Effect'],
  },
  {
    id: 'cat-12',
    slug: 'buku-alat-tulis',
    name: 'Buku & Alat Tulis',
    imageIcon: 'https://pngimg.com/uploads/book/book_PNG2111.png',
    description: 'Buku best-seller, novel inspiratif, buku bisnis/self-improvement, binder & pulpen.',
    bannerImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-12-1', slug: 'buku-self-improvement', name: 'Self-Improvement & Bisnis', itemCount: 160 },
      { id: 'sub-12-2', slug: 'novel-fiksi', name: 'Novel Fiksi Best-Seller', itemCount: 140 },
      { id: 'sub-12-3', slug: 'stationery', name: 'Journal & Pulpen Gel', itemCount: 120 },
    ],
    itemCount: 420,
    isPopular: false,
    featuredTags: ['Original Penerbit', 'Kertas Bookpaper', 'Bonus Bookmark'],
  },
];
