import { Order } from '../types/order';

export const mockOrders: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'CO-20260812-4819',
    userId: 'user-buyer-1',
    userName: 'Budi Santoso',
    userPhone: '081234567890',
    shippingAddress: {
      id: 'addr-1',
      label: 'Rumah Utama',
      recipientName: 'Budi Santoso',
      phone: '081234567890',
      fullAddress: 'Jl. Kemang Raya No. 42, RT 04 / RW 02, Kel. Bangka',
      district: 'Mampang Prapatan',
      city: 'Jakarta Selatan',
      province: 'DKI Jakarta',
      postalCode: '12730',
      isDefault: true,
    },
    storeOrders: [
      {
        sellerId: 'seller-3',
        sellerName: 'TechZone Gadget Store',
        sellerCity: 'Jakarta Pusat',
        sellerBadge: 'official',
        items: [
          {
            id: 'item-1',
            productId: 'prod-1',
            productTitle: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
            productSlug: 'sony-wh-1000xm5-wireless-noise-cancelling-headphones',
            productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
            variantSelected: 'Black Velvet',
            price: 4999000,
            quantity: 1,
            weightGrams: 500,
          },
        ],
        shipping: {
          id: 'ship-6',
          code: 'reguler',
          courierName: 'J&T Express',
          estimatedDays: '1-2 hari',
          price: 12000,
        },
        shippingCost: 12000,
        shippingDiscount: 12000,
        subtotal: 4999000,
        trackingNumber: 'JT8829104829',
        status: 'shipping',
        statusHistory: [
          {
            status: 'unpaid',
            title: 'Pesanan Dibuat',
            description: 'Menunggu pembayaran dari pembeli',
            timestamp: '2026-08-12T10:15:00Z',
          },
          {
            status: 'processing',
            title: 'Pembayaran Diterima',
            description: 'Penjual sedang menyiapkan pesanan dan mempacking dengan bubble wrap',
            timestamp: '2026-08-12T10:18:00Z',
          },
          {
            status: 'shipping',
            title: 'Paket Sedang Dikirim',
            description: 'Kurir J&T Express telah membawa paket menuju Hub Sortir Jakarta Selatan',
            timestamp: '2026-08-13T08:30:00Z',
          },
        ],
      },
      {
        sellerId: 'seller-1',
        sellerName: 'Brodo Footwear Official',
        sellerCity: 'Bandung',
        sellerBadge: 'official',
        items: [
          {
            id: 'item-2',
            productId: 'prod-4',
            productTitle: 'Brodo Heavyweight Oversized Tee - Cotton Combed 24s',
            productSlug: 'brodo-heavyweight-oversized-tshirt-24s',
            productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop',
            variantSelected: 'Forest Olive, L',
            price: 139000,
            quantity: 2,
            weightGrams: 560,
          },
        ],
        shipping: {
          id: 'ship-1',
          code: 'reguler',
          courierName: 'J&T Express Reguler',
          estimatedDays: '1-2 hari',
          price: 11000,
        },
        shippingCost: 11000,
        shippingDiscount: 8000,
        subtotal: 278000,
        trackingNumber: 'JT9928172901',
        status: 'processing',
        statusHistory: [
          {
            status: 'processing',
            title: 'Pesanan Sedang Diproses',
            description: 'Penjual sedang mengemas pesanan dari gudang Bandung',
            timestamp: '2026-08-13T11:00:00Z',
          },
        ],
      },
    ],
    itemsSubtotal: 5277000,
    totalShippingCost: 23000,
    totalDiscount: 20000,
    coinUsed: 10000,
    grandTotal: 5270000,
    paymentMethod: 'qris',
    paymentMethodName: 'QRIS Instant (GoPay/BCA/OVO/ShopeePay)',
    paymentStatus: 'paid',
    createdAt: '2026-08-12T10:15:00Z',
    updatedAt: '2026-08-13T08:30:00Z',
  },
  {
    id: 'ord-2',
    orderNumber: 'CO-20260805-1102',
    userId: 'user-buyer-1',
    userName: 'Budi Santoso',
    userPhone: '081234567890',
    shippingAddress: {
      id: 'addr-1',
      label: 'Rumah Utama',
      recipientName: 'Budi Santoso',
      phone: '081234567890',
      fullAddress: 'Jl. Kemang Raya No. 42, RT 04 / RW 02, Kel. Bangka',
      district: 'Mampang Prapatan',
      city: 'Jakarta Selatan',
      province: 'DKI Jakarta',
      postalCode: '12730',
      isDefault: true,
    },
    storeOrders: [
      {
        sellerId: 'seller-2',
        sellerName: 'Somethinc Beauty ID',
        sellerCity: 'Jakarta Barat',
        sellerBadge: 'official',
        items: [
          {
            id: 'item-3',
            productId: 'prod-5',
            productTitle: 'Somethinc 10% Niacinamide + Moisture Sabi Beet Brightening Serum',
            productSlug: 'somethinc-niacinamide-barrier-serum-20ml',
            productImage: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
            variantSelected: '40 ml Jumbo Big Value',
            price: 199000,
            quantity: 1,
            weightGrams: 90,
          },
        ],
        shipping: {
          id: 'ship-4',
          code: 'reguler',
          courierName: 'SiCepat BEST',
          estimatedDays: '1-2 hari',
          price: 10000,
        },
        shippingCost: 10000,
        shippingDiscount: 10000,
        subtotal: 199000,
        trackingNumber: 'SCP88192019',
        status: 'completed',
        statusHistory: [
          {
            status: 'completed',
            title: 'Pesanan Selesai',
            description: 'Pesanan telah diterima oleh Budi Santoso dan dana telah diteruskan ke penjual',
            timestamp: '2026-08-07T14:20:00Z',
          },
        ],
      },
    ],
    itemsSubtotal: 199000,
    totalShippingCost: 10000,
    totalDiscount: 10000,
    coinUsed: 5000,
    grandTotal: 194000,
    paymentMethod: 'bca_va',
    paymentMethodName: 'BCA Virtual Account',
    paymentStatus: 'paid',
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-08-07T14:20:00Z',
  },
];
