import { Product } from '../types/product';

export const mockProducts: Product[] = [
  // --- GADGET & ELEKTRONIK ---
  {
    id: 'prod-1',
    slug: 'sony-wh-1000xm5-wireless-noise-cancelling-headphones',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones - Hi-Res Audio Garansi Resmi TAM',
    description: 'Headphone flagship peredam bising terbaik di kelasnya dengan Auto NC Optimizer, 8 mikrofon beamforming untuk panggilan telepon super jernih, dan daya tahan baterai hingga 30 jam dengan fitur pengisian daya cepat.',
    price: 4999000,
    originalPrice: 5999000,
    stock: 24,
    soldCount: 840,
    rating: 4.9,
    reviewCount: 230,
    categoryId: 'cat-1',
    categorySlug: 'elektronik-gadget',
    subcategoryId: 'sub-1-3',
    sellerId: 'seller-3',
    sellerName: 'TechZone Gadget Store',
    sellerCity: 'Jakarta Pusat',
    sellerBadge: 'official',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Warna',
        options: [
          { id: 'v-xm5-black', name: 'Black Velvet', stock: 12 },
          { id: 'v-xm5-silver', name: 'Platinum Silver', stock: 8 },
          { id: 'v-xm5-blue', name: 'Midnight Blue (Special Edition)', priceModifier: 200000, stock: 4 },
        ],
      },
    ],
    specifications: [
      { label: 'Garansi', value: '1 Tahun Resmi PT Sony Indonesia' },
      { label: 'Baterai', value: 'Hingga 30 Jam (ANC On)' },
      { label: 'Bluetooth', value: 'v5.2 LDAC, AAC, SBC' },
      { label: 'Berat', value: '250 gram' },
    ],
    badges: ['flash_sale', 'official', 'gratis_ongkir'],
    weightGrams: 500,
    isFlashSale: true,
    flashSaleDiscount: 17,
    flashSaleStock: 15,
    flashSaleSold: 11,
    tags: ['Sony', 'Headphone', 'ANC', 'Hi-Res', 'TAM'],
    createdAt: '2026-01-10T10:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-2',
    slug: 'ugreen-nexode-pro-65w-gan-fast-charger-3-ports',
    title: 'UGREEN Nexode Pro 65W GaN Charger 3 Ports Type-C PD 3.0 QC 4.0 - Ultra Slim Portable',
    description: 'Charger GaN teknologi termutakhir generasi terbaru. 3 port (2 USB-C + 1 USB-A) mampu mengisi daya MacBook Pro, iPhone, iPad, dan smartphone Android secara bersamaan dengan perlindungan termal cerdas.',
    price: 349000,
    originalPrice: 599000,
    stock: 140,
    soldCount: 3200,
    rating: 4.9,
    reviewCount: 910,
    categoryId: 'cat-1',
    categorySlug: 'elektronik-gadget',
    subcategoryId: 'sub-1-4',
    sellerId: 'seller-3',
    sellerName: 'TechZone Gadget Store',
    sellerCity: 'Jakarta Pusat',
    sellerBadge: 'official',
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1622445262464-84b1456045b6?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Paket Bundling',
        options: [
          { id: 'v-ugreen-unit', name: 'Charger Saja', stock: 80 },
          { id: 'v-ugreen-cable', name: '+ Kabel C-to-C 100W 1M', priceModifier: 50000, stock: 60 },
        ],
      },
    ],
    specifications: [
      { label: 'Output Maksimal', value: '65 Watt GaN III' },
      { label: 'Port', value: '2x USB Type-C, 1x USB-A' },
      { label: 'Garansi', value: '18 Bulan Tukar Baru' },
    ],
    badges: ['terlaris', 'official', 'gratis_ongkir'],
    weightGrams: 180,
    tags: ['UGREEN', 'Charger 65W', 'GaN', 'MacBook', 'iPhone'],
    createdAt: '2026-02-01T08:00:00Z',
    isActive: true,
  },

  // --- FASHION PRIA ---
  {
    id: 'prod-3',
    slug: 'brodo-vulcano-leather-boots-vintage-brown',
    title: 'Brodo Vulcano Vintage Boots - Sepatu Kulit Asli Pull-Up Handcrafted Bandung',
    description: 'Sepatu boots ikonik dari Brodo menggunakan 100% Genuine Pull-Up Leather dengan sol karet TPR anti-slip berdaya cengkeram tinggi. Dibuat tangan oleh pengrajin handal di Bandung untuk ketahanan bertahun-tahun.',
    price: 749000,
    originalPrice: 999000,
    stock: 45,
    soldCount: 1850,
    rating: 4.9,
    reviewCount: 480,
    categoryId: 'cat-2',
    categorySlug: 'fashion-pria',
    subcategoryId: 'sub-2-3',
    sellerId: 'seller-1',
    sellerName: 'Brodo Footwear Official',
    sellerCity: 'Bandung',
    sellerBadge: 'official',
    images: [
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Warna',
        options: [
          { id: 'v-brodo-brown', name: 'Vintage Brown', stock: 25 },
          { id: 'v-brodo-black', name: 'Obsidian Black', stock: 20 },
        ],
      },
      {
        name: 'Ukuran',
        options: [
          { id: 'v-size-40', name: 'EU 40 (25.5 cm)', stock: 8 },
          { id: 'v-size-41', name: 'EU 41 (26.0 cm)', stock: 12 },
          { id: 'v-size-42', name: 'EU 42 (27.0 cm)', stock: 15 },
          { id: 'v-size-43', name: 'EU 43 (27.5 cm)', stock: 10 },
        ],
      },
    ],
    specifications: [
      { label: 'Bahan Upper', value: '100% Genuine Pull Up Leather' },
      { label: 'Outsole', value: 'Thermoplastic Rubber (TPR)' },
      { label: 'Konstruksi', value: 'Cementing + Blake Stitch' },
      { label: 'Asal Pembuatan', value: 'Bandung, Indonesia (Lokal Pride)' },
    ],
    badges: ['lokal_pride', 'official', 'gratis_ongkir', 'terlaris'],
    weightGrams: 1100,
    tags: ['Brodo', 'Sepatu Kulit', 'Boots', 'Lokal Pride', 'Pria'],
    createdAt: '2026-01-15T09:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-4',
    slug: 'brodo-heavyweight-oversized-tshirt-24s',
    title: 'Brodo Heavyweight Oversized Tee - Kaos Pria Cotton Combed 24s Premium Soft',
    description: 'Kaos oversized berpotongan boxy fit modern dengan gramasi tebal tidak menerawang namun tetap adem di iklim tropis. Kerah kokoh anti-melar dengan rib 1x1 elastis.',
    price: 139000,
    originalPrice: 199000,
    stock: 90,
    soldCount: 4200,
    rating: 4.8,
    reviewCount: 1120,
    categoryId: 'cat-2',
    categorySlug: 'fashion-pria',
    subcategoryId: 'sub-2-1',
    sellerId: 'seller-1',
    sellerName: 'Brodo Footwear Official',
    sellerCity: 'Bandung',
    sellerBadge: 'official',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Warna',
        options: [
          { id: 'v-tee-olive', name: 'Forest Olive', stock: 30 },
          { id: 'v-tee-black', name: 'Jet Black', stock: 40 },
          { id: 'v-tee-sand', name: 'Sand Khaki', stock: 20 },
        ],
      },
      {
        name: 'Ukuran',
        options: [
          { id: 'v-ts-s', name: 'S', stock: 20 },
          { id: 'v-ts-m', name: 'M', stock: 30 },
          { id: 'v-ts-l', name: 'L', stock: 25 },
          { id: 'v-ts-xl', name: 'XL', stock: 15 },
        ],
      },
    ],
    specifications: [
      { label: 'Bahan', value: 'Cotton Combed 24s 100%' },
      { label: 'Fitting', value: 'Relaxed Boxy Oversized' },
    ],
    badges: ['lokal_pride', 'official'],
    weightGrams: 280,
    tags: ['Kaos', 'Oversized', 'Brodo', 'Cotton Combed'],
    createdAt: '2026-02-05T11:00:00Z',
    isActive: true,
  },

  // --- KECANTIKAN & SKINCARE ---
  {
    id: 'prod-5',
    slug: 'somethinc-niacinamide-barrier-serum-20ml',
    title: 'Somethinc 10% Niacinamide + Moisture Sabi Beet Brightening Serum 20ml - BPOM Halal',
    description: 'Serum pencerah kulit dengan 10% Niacinamide dan ekstrak Sabiwhite 8x lebih efektif daripada Hydroquinone untuk memudarkan noda hitam bekas jerawat, meratakan warna kulit, dan memperkuat skin barrier.',
    price: 115000,
    originalPrice: 149000,
    stock: 120,
    soldCount: 15200,
    rating: 4.9,
    reviewCount: 3890,
    categoryId: 'cat-4',
    categorySlug: 'kecantikan-perawatan',
    subcategoryId: 'sub-4-1',
    sellerId: 'seller-2',
    sellerName: 'Somethinc Beauty ID',
    sellerCity: 'Jakarta Barat',
    sellerBadge: 'official',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1608248597359-0027732890a2?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Ukuran Botol',
        options: [
          { id: 'v-somethinc-20ml', name: '20 ml Regular', stock: 70 },
          { id: 'v-somethinc-40ml', name: '40 ml Jumbo Big Value', priceModifier: 84000, stock: 50 },
        ],
      },
    ],
    specifications: [
      { label: 'Nomor BPOM', value: 'NA18201901839' },
      { label: 'Sertifikasi', value: 'Halal MUI, Non-Comedogenic' },
      { label: 'Tipe Kulit', value: 'Semua jenis kulit / Kusam & Berjerawat' },
    ],
    badges: ['flash_sale', 'official', 'terlaris', 'gratis_ongkir'],
    weightGrams: 90,
    isFlashSale: true,
    flashSaleDiscount: 23,
    flashSaleStock: 40,
    flashSaleSold: 33,
    tags: ['Somethinc', 'Serum', 'Niacinamide', 'Brightening', 'Skincare'],
    createdAt: '2026-01-20T14:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-6',
    slug: 'somethinc-hooman-breathable-uv-cushion-spf35',
    title: 'Somethinc Hooman Breathable UV Cushion Cover SPF 35 PA++++ - Matte Poreless Finish',
    description: 'Cushion revolusioner dengan formula breathable berdaya tutup tinggi (medium-to-high coverage) yang menyamarkan pori-pori dan tahan minyak seharian tanpa rasa berat.',
    price: 175000,
    originalPrice: 220000,
    stock: 65,
    soldCount: 8400,
    rating: 4.8,
    reviewCount: 1980,
    categoryId: 'cat-4',
    categorySlug: 'kecantikan-perawatan',
    subcategoryId: 'sub-4-3',
    sellerId: 'seller-2',
    sellerName: 'Somethinc Beauty ID',
    sellerCity: 'Jakarta Barat',
    sellerBadge: 'official',
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Shade Warna Kulit',
        options: [
          { id: 'v-cushion-nina', name: 'Nina (Light Neutral)', stock: 20 },
          { id: 'v-cushion-charlotte', name: 'Charlotte (Medium Neutral)', stock: 25 },
          { id: 'v-cushion-coco', name: 'Coco (Medium Warm Tan)', stock: 20 },
        ],
      },
    ],
    specifications: [
      { label: 'SPF', value: 'SPF 35 PA++++' },
      { label: 'Finishing', value: 'Matte Breathable Longwear' },
      { label: 'Netto', value: '15 gram' },
    ],
    badges: ['official', 'gratis_ongkir'],
    weightGrams: 110,
    tags: ['Cushion', 'Somethinc', 'Makeup', 'SPF35'],
    createdAt: '2026-02-02T13:00:00Z',
    isActive: true,
  },

  // --- KOMPUTER & LAPTOP ---
  {
    id: 'prod-7',
    slug: 'keychron-k2-pro-wireless-custom-mechanical-keyboard',
    title: 'Keychron K2 Pro QMK/VIA Wireless Custom Mechanical Keyboard RGB Hot-Swappable',
    description: 'Mechanical keyboard nirkabel layout 75% kompak dengan dukungan kustomisasi QMK/VIA via browser. PBT Double-shot OSA keycaps, foam peredam suara silicon ganda, dan switch Gateron Jupiter yang super empuk.',
    price: 1450000,
    originalPrice: 1799000,
    stock: 22,
    soldCount: 650,
    rating: 4.9,
    reviewCount: 180,
    categoryId: 'cat-5',
    categorySlug: 'komputer-laptop',
    subcategoryId: 'sub-5-2',
    sellerId: 'seller-8',
    sellerName: 'MechGarage & Peripherals',
    sellerCity: 'Jakarta Barat',
    sellerBadge: 'star',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Tipe Switch',
        options: [
          { id: 'v-sw-red', name: 'Red Switch (Linear Silent)', stock: 10 },
          { id: 'v-sw-brown', name: 'Brown Switch (Tactile Bumpy)', stock: 8 },
          { id: 'v-sw-banana', name: 'Banana Switch (Early Bump Pro)', priceModifier: 50000, stock: 4 },
        ],
      },
    ],
    specifications: [
      { label: 'Konektivitas', value: 'Bluetooth 5.1 & Type-C Cable' },
      { label: 'Kompatibilitas', value: 'Mac, Windows, Linux, Android, iOS' },
      { label: 'Baterai', value: '4000 mAh (Hingga 300 jam)' },
      { label: 'Hot-Swap', value: 'Ya (3-pin & 5-pin compatible)' },
    ],
    badges: ['flash_sale', 'diskon_spesial', 'gratis_ongkir'],
    weightGrams: 1050,
    isFlashSale: true,
    flashSaleDiscount: 19,
    flashSaleStock: 10,
    flashSaleSold: 7,
    tags: ['Keyboard', 'Mechanical', 'Keychron', 'Hot-swap', 'Wireless'],
    createdAt: '2026-01-25T15:00:00Z',
    isActive: true,
  },

  // --- RUMAH TANGGA ---
  {
    id: 'prod-8',
    slug: 'carote-granite-non-stick-cookware-set-5pcs',
    title: 'CAROTE Granite Non-Stick Cookware Set 5 Pcs - Panci Penggorengan Anti Lengket Swiss Coating',
    description: 'Set perlengkapan dapur premium lapis granit Swiss 100% PFOA Free. Dilengkapi gagang kayu ergonomis stay-cool dan dasar induksi magnetik tebal yang menyalurkan panas merata dan hemat minyak.',
    price: 529000,
    originalPrice: 890000,
    stock: 35,
    soldCount: 1450,
    rating: 4.8,
    reviewCount: 420,
    categoryId: 'cat-6',
    categorySlug: 'rumah-tangga',
    subcategoryId: 'sub-6-1',
    sellerId: 'seller-4',
    sellerName: 'RumahKu Home & Living',
    sellerCity: 'Surabaya',
    sellerBadge: 'star',
    images: [
      'https://images.unsplash.com/photo-1584990347449-397a08b53272?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Varian Warna',
        options: [
          { id: 'v-carote-cream', name: 'Cozy Cream White', stock: 20 },
          { id: 'v-carote-sage', name: 'Sage Green Estetik', stock: 15 },
        ],
      },
    ],
    specifications: [
      { label: 'Isi Paket', value: 'Wok 28cm + Frypan 24cm + Casserole 24cm + 2 Tutup Kaca' },
      { label: 'Kompatibilitas Kompor', value: 'Gas, Induksi, Listrik, Keramik' },
      { label: 'Material', value: 'Aluminium Die-Cast dengan Swiss Granite Coating' },
    ],
    badges: ['terlaris', 'gratis_ongkir'],
    weightGrams: 3200,
    tags: ['Carote', 'Panci', 'Granite', 'Dapur', 'Anti Lengket'],
    createdAt: '2026-01-18T12:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-9',
    slug: 'nordic-minimalist-wooden-desk-lamp-led',
    title: 'Lampu Meja Nordic Minimalist Solid Oak Wood - Lampu Tidur Estetik Dimmer Touch',
    description: 'Lampu meja hias bergaya Scandinavian dengan rangka kayu solid Oak asli dan tudung kain linen bertekstur hangat. Dilengkapi kontrol sentuh untuk mengatur 3 tingkat keterangan cahaya (Warm, Natural, Cool White).',
    price: 189000,
    originalPrice: 280000,
    stock: 50,
    soldCount: 920,
    rating: 4.8,
    reviewCount: 290,
    categoryId: 'cat-6',
    categorySlug: 'rumah-tangga',
    subcategoryId: 'sub-6-2',
    sellerId: 'seller-4',
    sellerName: 'RumahKu Home & Living',
    sellerCity: 'Surabaya',
    sellerBadge: 'star',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=800&auto=format&fit=crop',
    ],
    specifications: [
      { label: 'Bahan', value: 'Kayu Ek Solid + Kap Linen Premium' },
      { label: 'Tegangan', value: 'USB 5V Safe Low Voltage' },
      { label: 'Dimensi', value: 'Tinggi 28cm x Diameter 14cm' },
    ],
    badges: ['diskon_spesial'],
    weightGrams: 650,
    tags: ['Lampu Meja', 'Estetik', 'Scandinavian', 'Dekorasi'],
    createdAt: '2026-02-04T10:00:00Z',
    isActive: true,
  },

  // --- MAKANAN & KOPI ---
  {
    id: 'prod-10',
    slug: 'arabika-gayo-aceh-specialty-coffee-beans-250g',
    title: 'Kopi Arabika Gayo Aceh Specialty Grade 1 - Biji Kopi / Bubuk Freshly Roasted 250gr',
    description: 'Biji kopi Arabika terbaik dari dataran tinggi Gayo Aceh pada ketinggian 1.500 mdpl. Notes: Dark Chocolate, Caramel, Floral, Citrus acidity yang seimbang dan aroma manis yang memikat.',
    price: 85000,
    originalPrice: 110000,
    stock: 80,
    soldCount: 3400,
    rating: 4.9,
    reviewCount: 880,
    categoryId: 'cat-7',
    categorySlug: 'makanan-minuman',
    subcategoryId: 'sub-7-1',
    sellerId: 'seller-6',
    sellerName: 'Warung Kopi Nusantara Artisan',
    sellerCity: 'Yogyakarta',
    sellerBadge: 'star',
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Bentuk Gilingan',
        options: [
          { id: 'v-grind-beans', name: 'Biji Utuh (Whole Beans)', stock: 35 },
          { id: 'v-grind-fine', name: 'Bubuk Halus (Espresso/Moka)', stock: 25 },
          { id: 'v-grind-medium', name: 'Bubuk Sedang (V60/Manual Brew)', stock: 20 },
        ],
      },
    ],
    specifications: [
      { label: 'Origin', value: 'Takengon, Aceh Tengah' },
      { label: 'Proses', value: 'Semi Washed' },
      { label: 'Roast Level', value: 'Medium Roast' },
      { label: 'Berat Bersih', value: '250 gram' },
    ],
    badges: ['lokal_pride', 'terlaris'],
    weightGrams: 280,
    tags: ['Kopi', 'Arabika', 'Gayo', 'Single Origin', 'Artisan'],
    createdAt: '2026-02-06T09:00:00Z',
    isActive: true,
  },

  // --- OUTDOOR & OLAHRAGA ---
  {
    id: 'prod-11',
    slug: 'eiger-rhinos-60l-carrier-backpack-outdoor',
    title: 'EIGER Rhinos 60L Carrier Backpack - Tas Gunung Ransel Hiking Ergonomic Backsystem',
    description: 'Tas carrier kapasitas 60 liter dengan teknologi Tropic Air Flow Backsystem yang menjaga sirkulasi udara di punggung tetap sejuk. Dilengkapi kompartemen water bladder, peluit darurat, dan rain cover tahan badai.',
    price: 1299000,
    originalPrice: 1599000,
    stock: 18,
    soldCount: 780,
    rating: 4.9,
    reviewCount: 310,
    categoryId: 'cat-8',
    categorySlug: 'olahraga-outdoor',
    subcategoryId: 'sub-8-3',
    sellerId: 'seller-5',
    sellerName: 'Eiger Adventure Hub',
    sellerCity: 'Bandung',
    sellerBadge: 'official',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
    ],
    variantGroups: [
      {
        name: 'Pilihan Warna',
        options: [
          { id: 'v-eiger-navy', name: 'Navy Blue / Orange', stock: 10 },
          { id: 'v-eiger-black', name: 'Charcoal Black', stock: 8 },
        ],
      },
    ],
    specifications: [
      { label: 'Kapasitas', value: '60 Liter' },
      { label: 'Bahan', value: 'Polyester 600D Tear-Resistant + Ripstop' },
      { label: 'Garansi', value: '1 Tahun Garansi Resmi EIGER Indonesia' },
    ],
    badges: ['official', 'lokal_pride', 'gratis_ongkir'],
    weightGrams: 1950,
    tags: ['Eiger', 'Carrier', 'Hiking', 'Tas Gunung', 'Outdoor'],
    createdAt: '2026-01-28T07:00:00Z',
    isActive: true,
  },

  // --- BUKU & LITERASI ---
  {
    id: 'prod-12',
    slug: 'atomic-habits-james-clear-edisi-bahasa-indonesia',
    title: 'Atomic Habits: Perubahan Kecil yang Memberikan Hasil Luar Biasa - James Clear (Gramedia Original)',
    description: 'Buku mega best-seller dunia panduan praktis membangun kebiasaan baik dan membuang kebiasaan buruk dengan sistem 1% lebih baik setiap hari. Buku 100% original berstiker hologram penerbit Gramedia.',
    price: 98000,
    originalPrice: 118000,
    stock: 150,
    soldCount: 9400,
    rating: 4.9,
    reviewCount: 2450,
    categoryId: 'cat-12',
    categorySlug: 'buku-alat-tulis',
    subcategoryId: 'sub-12-1',
    sellerId: 'seller-7',
    sellerName: 'Toko Buku Pustaka Cerdas',
    sellerCity: 'Yogyakarta',
    sellerBadge: 'star',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=800&auto=format&fit=crop',
    ],
    specifications: [
      { label: 'Penulis', value: 'James Clear' },
      { label: 'Penerbit', value: 'Gramedia Pustaka Utama' },
      { label: 'Jumlah Halaman', value: '356 Halaman' },
      { label: 'Bahasa', value: 'Bahasa Indonesia' },
    ],
    badges: ['terlaris', 'gratis_ongkir'],
    weightGrams: 350,
    tags: ['Atomic Habits', 'Buku Bisnis', 'Self Improvement', 'Gramedia'],
    createdAt: '2026-02-07T08:00:00Z',
    isActive: true,
  },
];
