import { Seller } from '../types/seller';

export const mockSellers: Seller[] = [
  {
    id: 'seller-1',
    username: 'brodo-official',
    name: 'Brodo Footwear Official',
    tagline: 'Sepatu & Fashion Pria Buatan Anak Bangsa Berkualitas Tinggi',
    description: 'Toko resmi Brodo Indonesia. Menyediakan koleksi sepatu kulit, sneakers harian, boots, sandal, dan pakaian pria dengan material terbaik buatan pengrajin lokal berstandar internasional.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1200&auto=format&fit=crop',
    badge: 'official',
    city: 'Bandung',
    province: 'Jawa Barat',
    rating: 4.9,
    totalProducts: 84,
    totalSold: 24500,
    responseRate: 99,
    responseSpeed: 'hitungan menit',
    joinedSince: '2021-03-10',
    followerCount: 142000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-1', code: 'reguler', courierName: 'J&T Express Reguler', estimatedDays: '1-2 hari', price: 11000, isFreeEligible: true },
      { id: 'ship-2', code: 'sameday', courierName: 'SiCepat Sameday', estimatedDays: '6-8 jam', price: 20000, isFreeEligible: false },
      { id: 'ship-3', code: 'instant', courierName: 'GoSend Instant', estimatedDays: '1-2 jam', price: 32000, isFreeEligible: false },
    ],
  },
  {
    id: 'seller-2',
    username: 'somethinc-store',
    name: 'Somethinc Beauty ID',
    tagline: 'Skincare & Makeup Lokal Halal Berkualitas Dermatologis',
    description: 'Official store produk Somethinc. Menghadirkan skincare formula mutakhir (Niacinamide, Hyaluronic, Bakuchiol) serta kosmetik cushion, lip tint yang ramah untuk kulit Asia.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=1200&auto=format&fit=crop',
    badge: 'official',
    city: 'Jakarta Barat',
    province: 'DKI Jakarta',
    rating: 4.9,
    totalProducts: 65,
    totalSold: 89000,
    responseRate: 98,
    responseSpeed: 'hitungan menit',
    joinedSince: '2020-08-15',
    followerCount: 380000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-4', code: 'reguler', courierName: 'SiCepat BEST', estimatedDays: '1-2 hari', price: 10000, isFreeEligible: true },
      { id: 'ship-5', code: 'instant', courierName: 'GrabExpress Instant', estimatedDays: '1-2 jam', price: 28000, isFreeEligible: false },
    ],
  },
  {
    id: 'seller-3',
    username: 'techzone-official',
    name: 'TechZone Gadget Store',
    tagline: 'Pusat Smartphone, Audio TWS & Aksesoris Gadget Garansi TAM',
    description: 'Authorized gadget distributor. Menjual smartphone flagship, earbuds TWS active noise cancelling, powerbank GaN fast charge 100% original bergaransi resmi.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
    badge: 'official',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    rating: 4.8,
    totalProducts: 120,
    totalSold: 47200,
    responseRate: 97,
    responseSpeed: '< 5 menit',
    joinedSince: '2021-11-20',
    followerCount: 95000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-6', code: 'reguler', courierName: 'J&T Express', estimatedDays: '1-2 hari', price: 12000, isFreeEligible: true },
      { id: 'ship-7', code: 'sameday', courierName: 'Anteraja Sameday', estimatedDays: '6-8 jam', price: 22000, isFreeEligible: false },
      { id: 'ship-8', code: 'instant', courierName: 'GoSend Instant', estimatedDays: '1-2 jam', price: 35000, isFreeEligible: false },
    ],
  },
  {
    id: 'seller-4',
    username: 'rumahku-living',
    name: 'RumahKu Home & Living',
    tagline: 'Perabot Minimalis Estetik & Perlengkapan Dapur Kekinian',
    description: 'Menjual perlengkapan rumah modern bergaya Scandinavian dan Japandi. Cookware anti-lengket granite coating, lampu tidur LED, dan rak organizer estetik.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200&auto=format&fit=crop',
    badge: 'star',
    city: 'Surabaya',
    province: 'Jawa Timur',
    rating: 4.8,
    totalProducts: 92,
    totalSold: 18300,
    responseRate: 96,
    responseSpeed: '10 menit',
    joinedSince: '2022-04-12',
    followerCount: 54000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-9', code: 'reguler', courierName: 'JNE REG', estimatedDays: '2-3 hari', price: 14000, isFreeEligible: true },
      { id: 'ship-10', code: 'cargo', courierName: 'J&T Cargo (Barang Besar)', estimatedDays: '3-5 hari', price: 45000, isFreeEligible: false },
    ],
  },
  {
    id: 'seller-5',
    username: 'eiger-outdoor',
    name: 'Eiger Adventure Hub',
    tagline: 'Perlengkapan Hiking, Camping, Sepeda & Petualangan Alam Bebas',
    description: 'Official gear store untuk pecinta outdoor dan olahraga. Tenda anti air, jaket windproof, tas carrier ergonomis, dan matras yoga berkualitas.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    badge: 'official',
    city: 'Bandung',
    province: 'Jawa Barat',
    rating: 4.9,
    totalProducts: 78,
    totalSold: 31000,
    responseRate: 98,
    responseSpeed: 'hitungan menit',
    joinedSince: '2021-01-10',
    followerCount: 210000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-11', code: 'reguler', courierName: 'SiCepat Reguler', estimatedDays: '1-2 hari', price: 11000, isFreeEligible: true },
      { id: 'ship-12', code: 'cargo', courierName: 'SiCepat Gokil (Cargo)', estimatedDays: '2-4 hari', price: 35000, isFreeEligible: false },
    ],
  },
  {
    id: 'seller-6',
    username: 'kopi-nusantara-co',
    name: 'Warung Kopi Nusantara Artisan',
    tagline: 'Biji Kopi Asli Single Origin & Camilan Khas Daerah',
    description: 'Menghadirkan kenikmatan kopi terbaik Indonesia langsung dari petani: Arabika Gayo Aceh, Toraja Sapan, Flores Bajawa, serta camilan keripik renyah tanpa pengawet.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=1200&auto=format&fit=crop',
    badge: 'star',
    city: 'Yogyakarta',
    province: 'DI Yogyakarta',
    rating: 4.9,
    totalProducts: 42,
    totalSold: 12500,
    responseRate: 99,
    responseSpeed: '< 10 menit',
    joinedSince: '2022-06-01',
    followerCount: 32000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-13', code: 'reguler', courierName: 'J&T Express', estimatedDays: '2 hari', price: 12000, isFreeEligible: true },
    ],
  },
  {
    id: 'seller-7',
    username: 'literasi-pustaka',
    name: 'Toko Buku Pustaka Cerdas',
    tagline: 'Buku Self Improvement, Bisnis, Fiksi 100% Original Penerbit',
    description: 'Distributor buku resmi Gramedia, Noura, Mizan, dan penerbit independen. Buku original berkualitas kertas prima dengan bonus pembatas buku eksklusif.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1507842229451-9f01079ca4b5?q=80&w=1200&auto=format&fit=crop',
    badge: 'star',
    city: 'Yogyakarta',
    province: 'DI Yogyakarta',
    rating: 4.9,
    totalProducts: 150,
    totalSold: 29000,
    responseRate: 98,
    responseSpeed: 'hitungan menit',
    joinedSince: '2021-09-18',
    followerCount: 68000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-14', code: 'reguler', courierName: 'Anteraja Reguler', estimatedDays: '2 hari', price: 11000, isFreeEligible: true },
    ],
  },
  {
    id: 'seller-8',
    username: 'mech-garage-id',
    name: 'MechGarage & Peripherals',
    tagline: 'Custom Mechanical Keyboard, Mouse Gaming & Desk Setup',
    description: 'Spesialis keyboard mekanikal hotswap, keycaps PBT dye-sub, switch tactile/linear, custom coiled cable, dan mouse ultra-lightweight untuk gamer dan profesional.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop',
    badge: 'star',
    city: 'Jakarta Barat',
    province: 'DKI Jakarta',
    rating: 4.9,
    totalProducts: 55,
    totalSold: 9800,
    responseRate: 97,
    responseSpeed: '< 15 menit',
    joinedSince: '2023-02-14',
    followerCount: 41000,
    isVerified: true,
    supportedShippings: [
      { id: 'ship-15', code: 'reguler', courierName: 'J&T Express', estimatedDays: '1-2 hari', price: 10000, isFreeEligible: true },
      { id: 'ship-16', code: 'instant', courierName: 'GoSend Instant', estimatedDays: '1-2 jam', price: 29000, isFreeEligible: false },
    ],
  },
];
