import { Voucher } from '../types/voucher';

export const mockVouchers: Voucher[] = [
  {
    id: 'vouch-1',
    code: 'ONGKIRGRATIS',
    title: 'Gratis Ongkir Xtra s/d Rp20.000',
    description: 'Potongan ongkos kirim ke seluruh Indonesia untuk semua metode pengiriman reguler.',
    type: 'free_shipping',
    discountAmount: 20000,
    minPurchase: 50000,
    expiresAt: '2026-08-31T23:59:59Z',
    usageCount: 840,
    usageLimit: 5000,
  },
  {
    id: 'vouch-2',
    code: 'COINAJAPESTA',
    title: 'Diskon 10% Spesial Launching',
    description: 'Diskon 10% belanja apa saja tanpa batas kategori, maksimal potongan Rp50.000.',
    type: 'discount_percent',
    discountAmount: 10,
    maxDiscount: 50000,
    minPurchase: 100000,
    expiresAt: '2026-08-31T23:59:59Z',
    usageCount: 1200,
    usageLimit: 3000,
  },
  {
    id: 'vouch-3',
    code: 'KOINCASHBACK',
    title: 'Cashback Koin 15% s/d 30rb Koin',
    description: 'Dapatkan cashback koin COinaja untuk belanja berikutnya tanpa syarat ribet.',
    type: 'cashback_coin',
    discountAmount: 15,
    maxDiscount: 30000,
    minPurchase: 75000,
    expiresAt: '2026-08-31T23:59:59Z',
    usageCount: 450,
    usageLimit: 2000,
  },
  {
    id: 'vouch-4',
    code: 'BRODOVVIP',
    title: 'Diskon Rp30.000 Toko Brodo Official',
    description: 'Potongan belanja langsung khusus produk Brodo Footwear Official.',
    type: 'discount_fixed',
    discountAmount: 30000,
    minPurchase: 250000,
    sellerId: 'seller-1',
    sellerName: 'Brodo Footwear Official',
    expiresAt: '2026-08-31T23:59:59Z',
    usageCount: 130,
    usageLimit: 500,
  },
  {
    id: 'vouch-5',
    code: 'SOMETHINCGLOW',
    title: 'Voucher Toko Somethinc Rp15.000',
    description: 'Potongan langsung untuk pembelian produk skincare Somethinc.',
    type: 'discount_fixed',
    discountAmount: 15000,
    minPurchase: 100000,
    sellerId: 'seller-2',
    sellerName: 'Somethinc Beauty ID',
    expiresAt: '2026-08-31T23:59:59Z',
    usageCount: 210,
    usageLimit: 1000,
  },
];
